Updates build scripts.

diff --git a/script/test b/script/test
--- a/script/test
+++ b/script/test
@@ -6,6 +6,7 @@ source script/.env
 source script/script_hooks/schemes
 source script/script_hooks/destinations
 source script/common/carthage
+source script/common/swiftlint
 
 run_tests ()
 {
@@ -20,18 +21,9 @@ run_tests ()
 
   destination=$(scheme_destination $1)
   test_command="$test_command -destination $destination clean build test -configuration Debug"
-
-  if [ ! -z "$CIRCLE_ARTIFACTS" ]
-  then
-    test_command="$test_command | tee $CIRCLE_ARTIFACTS/xcode_raw.log"
-  fi
   if type bundle > /dev/null && bundle show xcpretty > /dev/null
   then
     test_command="$test_command | bundle exec xcpretty -c"
-    if [ ! -z "$CIRCLE_TEST_REPORTS" ]
-    then
-      test_command="$test_command --report junit --output $CIRCLE_TEST_REPORTS/xcode/results.xml"
-    fi
   fi
 
   echo ""
@@ -49,6 +41,27 @@ then
   check_carthage_version
 fi
 
+if [ -f .swiftlint.yml ] && [ -z $DISABLE_SWIFTLINT ]
+then
+  echo ""
+  echo " → Running swiftlint"
+  echo ""
+  check_swiftlint_version
+  if [ ! -z "$RUNNING_ON_CI" ] && type bundle > /dev/null && bundle show linterbot > /dev/null && [ "$PULL_REQUEST" != "false" ]
+  then
+    echo ""
+    echo " → Running linterbot"
+    echo ""
+    # || true avoid a the script to fail if the linter
+    # does not returns successfully, which could happen
+    # in case of severe lint errors
+    swiftlint lint --reporter json > .swiftlint-report.json || true
+    bundle exec linterbot $REPO_SLUG $PULL_REQUEST < .swiftlint-report.json
+  else
+    swiftlint
+  fi
+fi
+
 current_schemes=$(schemes)
 if [ -z "$current_schemes" ]
 then
@@ -62,16 +75,16 @@ do
   run_tests $scheme
 done
 
-if [ -f "$PROJECT_NAME.podspec" ]
+if [ -f "$PROJECT_NAME.podspec" ] && [ "$LINT_PODSPEC" == "yes"]
 then
   echo ""
   echo " → Linting $PROJECT_NAME.podspec"
   echo ""
   if type bundle > /dev/null && bundle show pod > /dev/null
   then
-    bundle exec pod lib lint
+    bundle exec pod lib lint $LINT_PODSPEC_PARAMETERS
   elif type pod > /dev/null
   then
-    pod lib lint
+    pod lib lint $LINT_PODSPEC_PARAMETERS
   fi
 fi
